### ISSUE TITLE
Dark mode support for block images

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/prefect-ui-library#1101]
<img width="127" alt="image" src="https://user-images.githubusercontent.com/6776415/216138540-07f62180-5838-4522-a1c3-dc3b4a7b3d8e.png">

Possible solutions
- a rounded background color (sort of like apps on an iPhone) might do

**Comment by pleek91** [comment]
These images can be user provided. So this will have to be pretty flexible.

**Comment by pleek91** [comment]
Closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1142
