### ISSUE TITLE
Add header to deployment table schedule toggle

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect-ui-library#1107]
The deployment table does not identify what the toggle on the far right indicates (whether the schedule is paused or active) as you can see in this screenshot:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/13255838/216404052-686aff35-0da0-497e-bd80-4f3be97c8cee.png">

**Comment by zhen0** [comment]
Add schedule column and add "Schedule active" header to it

**Comment by pleek91** [comment]
This is no longer relevant since the deployment page was combined with the flow and the toggle is presented with the schedule label


![Image](https://github.com/PrefectHQ/prefect-ui-library/assets/6200442/87e41caa-3649-4212-aabc-775ebe4c4175)
