### ISSUE TITLE
Bug: On flowRuns page when selecting a queue, all queues with the same name get selected

### ISSUE THREAD

**Issue by marichka-offen** [PrefectHQ/prefect-ui-library#1118]
<img width="816" alt="Screenshot 2023-02-06 at 11 42 36 AM" src="https://user-images.githubusercontent.com/40467112/217031753-50878752-e3f0-4561-9af0-6bc455861ab4.png">

**Comment by zhen0** [comment]
Should be fixed by https://github.com/PrefectHQ/orion-design/pull/1131
