### ISSUE TITLE
Adding additional Deployment fields to UI 

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect-ui-library#1242]
There are a couple fields during deployment that don't appear in the UI, but are visible from the deployment.yaml created from a deployment.

In the interest of visibility, and potential troubleshooting, I think these are useful fields to be visible in the ui.

Namely, `entrypoint` and `path`.

`entrypoint` can be a fully qualified path, or a relative path, but can be useful information when identifying the file path of a flow location in a deployment.

`path` is prepended to the entrypoint and can be either a full path, or again a relative path from root (up to , but not including the flow itself). 

Consequently, having these two visible in the UI make finding configuration details on a deployment easier as the only other location this information is present, is either in the flow logs (when retrieving), or in the deployment.yaml manifest generated at build time. 

![image](https://user-images.githubusercontent.com/105737359/226977621-81399e84-2562-4e91-8fe0-894edcba25db.png)

**Comment by znicholasbrown** [comment]
@prefectcboyd do you think these parameters should be editable as well? trying to figure out if those should be read-only for the UI's purposes; I assume updating either of those means storage has changed/flow has moved which I would _expect_ means the deployment needs to be reapplied

**Comment by prefectcboyd** [comment]
That's a good question - if they are edited, then it would require updating and applying the deployment. I don't know if that's possible / feasible from the UI - if it is, I think it would enable some quicker updates as opposed to re-running pipelines or build commands, but I think read-only is equally viable to ensure consistency with a declarative approach (requiring `deployment build`)
