### ISSUE TITLE
Navigating the UI produces a lot of 403 errors

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/prefect-ui-library#1256]
When navigating around in the UI, 403 errors seem to pile up quite a bit in the console:

![Image](https://user-images.githubusercontent.com/6776415/227303796-7f7e1016-30fe-437c-813f-8e733f71fd5b.png)

I generally see the data I expect regardless, but something to clean up.

**Comment by pleek91** [comment]
@brandonreid are you still seeing this? I was unable to reproduce. If you're not able to reproduce anymore let's close this issue for now.

**Comment by pleek91** [comment]
@brandonreid closing this. We can reopen or create a new issue if we see this again and have a reproduction.
