### ISSUE TITLE
Log messages extend outside the container

### ISSUE THREAD

**Issue by frctnlss** [PrefectHQ/prefect-ui-library#1341]
## Problem

Log messages extend outside the container and cause readability issues. See the below image taken after [this merge request was completed](https://github.com/PrefectHQ/prefect-ui-library/pull/1334)

## Expected behavior:

Log messages regardless of length would wrap or induce a horizontal scroll if it would extend outside the container

## Code Generating Logs

```python
command = ['dbt', '--no-use-colors', 'test', '--target', 'main']
logger = prefect.get_run_logger()
logger.info(f"Running {command} from {os.getcwd()}")
output = subprocess.Popen(command, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
while output.poll() is None:
  line = output.stdout.readline().decode("utf-8", "ignore").strip()
  error_condition = #code to set a bool
  if error_condition:
    logger.error(line)
  else:
    logger.info(line)
```

## Additional Information

We are intentionally not using the communicate method because the logs are verbose and would require larger compute constraints

We are also intentionally not using the dbt prefect task because of the added complexity inherent in managing blocks that could otherwise be codified. Our codebase is a result of migrating from Prefect 1 and the decisions we needed to make to migrate all of our pipelines efficiently.

## Artifacts

[Community Slack thread](https://prefect-community.slack.com/archives/C0192RWGJQH/p1681135372018279) where the conversation on this started.

![image](https://user-images.githubusercontent.com/44410965/231534606-a65158d0-0b74-447b-a1f2-a66dd004e567.png)

**Comment by pleek91** [comment]
@frctnlss thanks for the reproduction snippet. I was able to reproduce without long words and make another fix that should solve this for real this time 😄

**Comment by frctnlss** [comment]
Not sure what is going on here. The log text is getting cut off instead of wrapping. The header and supplemental information are extended to the end of the log and overlapping run metadata. 

![image](https://user-images.githubusercontent.com/44410965/232067712-e747c572-cd8c-4fa6-9a00-746463af6af1.png)
