### ISSUE TITLE
Integration into an Angular app

### ISSUE THREAD

**Issue by LelouchOfTheResurrection** [PrefectHQ/prefect-ui-library#1455]
I have zero knowledge of vue.js and I want to use this library into my angular project. Is this doable? if so, any idea how difficult or easy it is just to be able to use the components in this library into a blank angular app?

**Comment by pleek91** [comment]
@LelouchOfTheResurrection technically this is possible but not something we officially support. I'm going to close this issue. I'd suggest stackoverflow as a good place to find some answers.
