### ISSUE TITLE
Work Pool creation/edit not respecting required fields

### ISSUE THREAD

**Issue by jakekaplan** [PrefectHQ/prefect-ui-library#1568]
When creating a WorkPool, there can be a number of form fields that can required. The UI used to validate these fields before letting you proceed to creating a work pool.

Repro:
1. Create an `AzureContainerInstance` WorkPool
2. Fill in no options for the base job template (note that `resource_group_name` and `subscription_id` and required in the response from `/views/aggregate-worker-metadata`)
3. Observe the work pool is created successfully

![Screenshot 2023-07-11 at 12 00 41 PM](https://github.com/PrefectHQ/prefect-ui-library/assets/40362401/2b056161-330d-423b-8a46-042b91b769e4)
![Screenshot 2023-07-11 at 12 01 36 PM](https://github.com/PrefectHQ/prefect-ui-library/assets/40362401/e24a9a52-714d-45c8-928c-8894c3dfd331)
![Screenshot 2023-07-11 at 12 01 55 PM](https://github.com/PrefectHQ/prefect-ui-library/assets/40362401/e6148209-50a1-4f05-a561-7bc4d8165d2f)

**Comment by znicholasbrown** [comment]
Ah - this was an expected regression from https://github.com/PrefectHQ/prefect-ui-library/pull/1560 but will be un-regressed (re-regressed? fixed.) with the release of [this code](https://github.com/PrefectHQ/prefect-ui-library/pull/1563/files#diff-409b374c9773e44409b3c49819e4c15ac1da5a2196953ddf58b124ff24b3dea7R109-R113). Given that the fix is already merged, I'm going to close this.

**Comment by WillRaphaelson** [comment]
Thanks @znicholasbrown - if theres not a planned release of this by noon tomorrow could we get one out the door?

**Comment by znicholasbrown** [comment]
Yup 👍🏻

**Comment by znicholasbrown** [comment]
Just kidding, while what I said was true as well, the work pool creation wizard didn't have a validation observer on the infra creation step -[this PR](https://github.com/PrefectHQ/prefect-ui-library/pull/1570) adds one and will close this issue properly.

Resolved by: https://github.com/PrefectHQ/prefect-ui-library/pull/1570

**Comment by znicholasbrown** [comment]
#1570 is merged and will go out with the next release (today or tomorrow)
