### ISSUE TITLE
Bug: Dashboard flow runs select isn't informative on mobile

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect-ui-library#1579]
When on <md screens, tabs are correctly condensed to a mobile select but with the following options:

<img width="519" alt="Screenshot 2023-07-13 at 6 39 25 PM" src="https://github.com/PrefectHQ/prefect-ui-library/assets/27291717/dd915d5e-fea3-47cc-a6e0-0a214c2e62c9">

**Comment by AmanSal1** [comment]
@zhen0  No I am not

**Comment by zhen0** [comment]
Hmm!  Now you've replied I can assign you! ✅

**Comment by zhen0** [comment]
Looks like the numbers in the drop down are also a bit off. We can add to a separate issue if easier for you Aman Sal.  Adding labels to the dropdown is the main scope of this issue. 

<img width="319" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/40272060/5f39f2cf-7898-4d58-8ec4-a71454ae21a1">
<img width="765" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/40272060/7f16935b-b272-4658-9558-e27195b75c46">

**Comment by zhen0** [comment]
Should now be resolved on smaller screens

**Comment by zhen0** [comment]
<img width="363" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/40272060/14b22033-9182-43f5-8f20-3b82e1ac715b">
