### ISSUE TITLE
Enhancement: Disambiguate work queues belonging to work pools

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/prefect-ui-library#1623]
**Summary**

When creating a work pool, a `default` work queue is created. Some selections do not display the corresponding work pool, so it is ambiguous which is which.

![image](https://github.com/PrefectHQ/prefect-ui-library/assets/52710/1ad79325-da2e-4b2f-aead-fcde3f0136fb)

Reported by [a user in the Prefect Slack community](https://prefect-community.slack.com/archives/C0192RWGJQH/p1691178362176129)

This is similar to #1118

**Comment by taylor-curran** [comment]
Noting a +1 from a user on this issue.

**Comment by zhen0** [comment]
I expect that upcoming updates to worker status will overtake the need for this.
