### ISSUE TITLE
Deployment page run filters should persist between page refreshes

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect-ui-library#1758]
On most pages we codify any filters in the URL so they persist between refreshes and can be shared. The deployment page doesn't do this and should

**Comment by taylor-curran** [comment]
I have had this requested from over a dozen users.

**Comment by znicholasbrown** [comment]
Yup this is still an issue - for example this deployment:
https://app.stg.prefect.dev/account/9a67b081-4f14-4035-b000-1f715f46231b/workspace/60305128-9439-47ef-b353-f2a8f6a7a8b4/deployments/deployment/acb27869-2737-4614-8349-2b4cbc25ad07

if you were to select just "Failed" runs from the dropdown and then refresh, the filter would be gone
