### ISSUE TITLE
Combine Flow list page components into new updated one

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/prefect-ui-library#1763]
Currently we have 2 components for the Flows page. Nebula and OSS are using different ones, which we don't want.

### `FlowList.vue` component

<img width="1256" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/6776415/af2b2ec6-864e-4453-b9d1-af6a8364dd53">

This is used in OSS and includes the most recent and next flow run. It also has stuff we don't need since we returned the Deployments page.

### `FlowsTable.vue` component

<img width="1250" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/6776415/5ef772b8-a817-453b-8667-b24deae13dfc">

This is used in Nebula and has been around for a long time.

## The new combined design ✨

![image](https://github.com/PrefectHQ/prefect-ui-library/assets/6776415/d3ef5ffb-6c57-4660-9128-9665796265e7)

_[See Figma for the most updated design](https://www.figma.com/file/PyPlB33BgW3zw8YTpufeSf/Flow-%2F-Task-%2F-Scheduled-Runs?type=design&node-id=10-8268&mode=design&t=ZP5yi0XQskIIa1d2-4)_

This version combines a couple elements into the table. A few things to note:

- At the prefect-design level
  - [ ] The column header styling is updated here to have smaller, subdued text. Let's update this in prefect-design for all tables as part of this effort.
  - [ ] We're introducing an "inline" variant of a select menu for use in the "Activity" table column header where the user can select from `8h | 24h | 1w`. This may well be a one-off pattern, so we can build this into this component or make it a part of prefect-design, dealers choice.
  - [ ] The `PIconButtonMenu` component needs a `flat` variant (forwarding the `flat` prop to the trigger) so it's less heavy in the table.
- [ ] We're introducing a new "condensed" (prop name tbd) variant of the StateBadge, where only the icon is shown using the bg color of the badge as the icon color. This should have a tooltip on hover that reads out the state name.
- [ ] We're swapping the older bar graph that's on the Nebula flows page today with the mini variant of the `FlowRunsBarChart` component.
- [ ] The sort menu is getting 2 additional options, "Deployments asc" and "Deployments desc" so it's easier to audit flows and their deployment assignments.

**Comment by pleek91** [comment]
Closing because they are both using `FlowList` now.
