### ISSUE TITLE
prefect 2.14.6 `Copied to clipboard` raise error `TypeError: Cannot read properties of undefined (reading 'writeText')`

### ISSUE THREAD

**Issue by Ox0400** [PrefectHQ/prefect-ui-library#1893]
prefect 2.14.6 `Copied to clipboard` raise error `TypeError: Cannot read properties of undefined (reading 'writeText')`

```
index-ede2aed2.js:1 TypeError: Cannot read properties of undefined (reading 'writeText')
    at MO (index-ede2aed2.js:67:39515)
    at j.onClick.i.<computed>.i.<computed> (index-ede2aed2.js:113:22432)
    at db (index-ede2aed2.js:1:14649)
    at tu (index-ede2aed2.js:1:14728)
    at HTMLButtonElement.i (index-ede2aed2.js:1:70379)

```

Source code. 
```
function MO(e, t="Copied to clipboard!") {
    navigator.clipboard.writeText(e),
    je(t, "success")
}
```

**Comment by zhen0** [comment]
Hi @Ox0400 - can you give more information about when and where you are seeing this error - perhaps with some steps to reproduce?  Thanks!

**Comment by Ox0400** [comment]
> Hi @Ox0400 - can you give more information about when and where you are seeing this error - perhaps with some steps to reproduce? Thanks!

On deployment page,  it's look like because of i was deploy the server on my local and not enable https.

**Comment by serinamarie** [comment]
I'm not exactly sure what to make of this issue, closing this as not planned. Feel free to open a new issue with added clarity if it persists!
