### ISSUE TITLE
Bug: `Custom` schema form list inputs don't react to whitespace changes

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect-ui-library#1941]
As the title states, we've observed that copy/pasting a value like:
```json
[
  "HelloWorld",
]
```
into a `list[str]` typed input on the `Custom` tab of the parameters form and then modifying the input to match:
```json
[
  "Hello World",
]
```
appears to work but when the form is submitted the original:
```json
[
  "HelloWorld",
]
```
is what's actually submitted.

**Comment by taylor-curran** [comment]
This is important to a customer of mine. Thank you Nicholas for reproducing!

**Comment by znicholasbrown** [comment]
I'll add more detail to this as I investigate, for now I've been able to repro this when using the "Copy to new run" feature

**Comment by pleek91** [comment]
@znicholasbrown would you be able to help me reproduce this and test if this is fixed in the new ui?

**Comment by znicholasbrown** [comment]
Yup - this looks to be fixed in the new UI, tried modification post-paste, copy to new run, and typing directly and couldn't repro.

Used this flow:

```py
from typing import List
from prefect import flow

@flow
def prefect_ui_library_1941(arr: List[str] = []):
  pass

if __name__ == '__main__':
    prefect_ui_library_1941.serve(
       name='default',
    )
```
