### ISSUE TITLE
Feature Request -> Date Range CurrentTime Around

### ISSUE THREAD

**Issue by japerry911** [PrefectHQ/prefect-ui-library#1993]
Add feature so that you can have a Current_Time Around a Time filter.

Like set to 24 hours so everything in chart filter view is shown 24 hours before and ahead.

Like the current Around a Time filter, but Now checkbox would be currentTime() .

Let me know if that makes sense, or you need more info or anything, happy to provide.

Thank you!

**Comment by zhen0** [comment]
Thanks for the suggestion @japerry911 💯
