### ISSUE TITLE
Flow runs bar chart popover cutoff by table

### ISSUE THREAD

**Issue by collincchoy** [PrefectHQ/prefect-ui-library#2206]
There's an overflow/stacking issue with the flow runs bar chart popover (`flow-runs-bar-chart__pop-over`) from within the Deployments table. 

See in the below screenshot that with a few deployments, the popover when hovering over the flow runs bars is completely hidden. 

> [!Note]
>  the pink line is added for visual effect and not a part of normal behavior.

![image](https://github.com/PrefectHQ/prefect-ui-library/assets/22418768/d64382ac-f29a-4806-9056-964850da166f)

The Deployments table (via `p-table`) has `overflow: hidden` and this popover doesn't portal out so it gets hidden.

**Comment by dylanbhughes** [comment]
Referenced in Community: https://prefect-community.slack.com/archives/C0192RWGJQH/p1717891820849509
