### ISSUE TITLE
ReferenceError: backupRandomUUID is not defined

### ISSUE THREAD

**Issue by Ox0400** [PrefectHQ/prefect-ui-library#2492]
<img width="948" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/5310853/4e144468-1c73-4969-9eb8-1b737f9775dc">

**Comment by Ox0400** [comment]
I created a PR for fix this issue , https://github.com/PrefectHQ/vue-charts/pull/357

**Comment by pleek91** [comment]
Thank you!
