### ISSUE TITLE
Flow runs bar chart popover title overflows out of popover

### ISSUE THREAD

**Issue by collincchoy** [PrefectHQ/prefect-ui-library#2543]
Long flow or run names overflow out of the popover

<img width="692" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/22418768/6b217044-6960-4979-88c3-9b1961ba390d">

<img width="595" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/22418768/20f8a797-1dc9-4888-84ad-8c4ce31645b7">

**Comment by pleek91** [comment]
It appears that these breadcrumbs are wrapping now. 
<img width="418" alt="image" src="https://github.com/PrefectHQ/prefect-ui-library/assets/6200442/3525402f-9bee-467a-b1fd-395d30183596">

**Comment by pleek91** [comment]
Never mind, the deployment page specifically this doesn't work. Looking into why. Re-opening until I figure that out. 
![image](https://github.com/PrefectHQ/prefect-ui-library/assets/6200442/8b6f73ce-9dc5-4732-939a-912c851a2738)
