### ISSUE TITLE
Bug: startDate/endDate filter doesn't reset when pressing 'Clear Filters' button

### ISSUE THREAD

**Issue by marichka-offen** [PrefectHQ/prefect-ui-library#703]
When clearing out filters, Start/EndDate does not reset like the rest of the filters. The list of items is rendered as if all filters are reset, but Start/EndDate stays the same in the UI

https://user-images.githubusercontent.com/40467112/196969836-0ca7aaaf-755d-4e99-844d-2cc460dbef95.mov

**Comment by pleek91** [comment]
This was specifically tested as part of https://github.com/PrefectHQ/prefect-ui-library/pull/1174 and was working. So I'm closing this issue.
