### ISSUE TITLE
Review default tab

### ISSUE THREAD

**Issue by gabcoyne** [PrefectHQ/prefect-ui-library#943]
User feedback was that generally runs was where they wanted to look, description is used more for users that are not as familiar with the workloads and need reference but those navigating more frequently were looking for run information.

![image (4)](https://user-images.githubusercontent.com/9196875/208942484-e9df9f96-69ea-40d1-b84e-45e6fdb79621.png)

**Comment by pleek91** [comment]
Closed by https://github.com/PrefectHQ/nebula-ui/pull/2282
